---
title: "607_Project1_DylanGold"
format: html
editor: visual
---
# 607 Project 1 Dylan Gold

## Approach

In this assignment we have to parse a text file that was given to us and use the information in the file to generate a pre-chess rating of all the opponents.
Once we do this we create a csv with the Player’s Name, Player’s State, Total Number of Points, Player’s Pre-Rating, and Average Pre Chess Rating of Opponents.

The initial challenge is parsing the text file. All the information is on the row plaintext except for the average pre-chess rating of opponents.
For this we need to also store every match and use this information to get the average pre-chess rating. 
Because the data is separated by | for each entry we could probably use this to split the information. This might be easier in python with its built in split but it looks like R has str_split() as well which should make it easier. We can try some regex for separating the wins and player in each round, though it would probably be easier to just take the first character for the win status.

I will create a data frame with csv output format we need then write.csv() to create our csv.

